"""new table

Revision ID: 9f7ecf49ce79
Revises: 45b2de0900c1
Create Date: 2023-05-15 16:15:50.477699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7ecf49ce79'
down_revision = '45b2de0900c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
